name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v2

      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build image
        run: |
          export DOCKER_BUILDKIT=1
          docker build -t api:latest --ssh default .

      - name: Test image
        run: |
          docker run api:latest tox